// Here, the uuid will be generated for administrator
// and employee users, as the application does not 
// have a backend for them to be generated by a database.

const { v4: uuidv4 } = require('uuid');

let myuuid = uuidv4();

export default myuuid;
